// Code generated by protoc-gen-go. DO NOT EDIT.
// source: types.proto

/*
Package hexatype is a generated protocol buffer package.

It is generated from these files:
	types.proto

It has these top-level messages:
	Entry
	KeylogIndex
	ReqResp
	RequestOptions
*/
package hexatype

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import hexaring "github.com/hexablock/hexaring"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Hexalog entry
type Entry struct {
	Previous  []byte `protobuf:"bytes,1,opt,name=Previous,proto3" json:"Previous,omitempty"`
	Timestamp uint64 `protobuf:"varint,2,opt,name=Timestamp" json:"Timestamp,omitempty"`
	Height    uint32 `protobuf:"varint,3,opt,name=Height" json:"Height,omitempty"`
	Key       []byte `protobuf:"bytes,4,opt,name=Key,proto3" json:"Key,omitempty"`
	Data      []byte `protobuf:"bytes,5,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (m *Entry) Reset()                    { *m = Entry{} }
func (m *Entry) String() string            { return proto.CompactTextString(m) }
func (*Entry) ProtoMessage()               {}
func (*Entry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Entry) GetPrevious() []byte {
	if m != nil {
		return m.Previous
	}
	return nil
}

func (m *Entry) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Entry) GetHeight() uint32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *Entry) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *Entry) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type KeylogIndex struct {
	Key     []byte   `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Height  uint32   `protobuf:"varint,2,opt,name=Height" json:"Height,omitempty"`
	Marker  []byte   `protobuf:"bytes,3,opt,name=Marker,proto3" json:"Marker,omitempty"`
	Entries [][]byte `protobuf:"bytes,4,rep,name=Entries,proto3" json:"Entries,omitempty"`
}

func (m *KeylogIndex) Reset()                    { *m = KeylogIndex{} }
func (m *KeylogIndex) String() string            { return proto.CompactTextString(m) }
func (*KeylogIndex) ProtoMessage()               {}
func (*KeylogIndex) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *KeylogIndex) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *KeylogIndex) GetHeight() uint32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *KeylogIndex) GetMarker() []byte {
	if m != nil {
		return m.Marker
	}
	return nil
}

func (m *KeylogIndex) GetEntries() [][]byte {
	if m != nil {
		return m.Entries
	}
	return nil
}

// Request and response shared structure for hexalog
type ReqResp struct {
	// ID is based on the request/response
	ID      []byte          `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Entry   *Entry          `protobuf:"bytes,2,opt,name=Entry" json:"Entry,omitempty"`
	Options *RequestOptions `protobuf:"bytes,3,opt,name=Options" json:"Options,omitempty"`
}

func (m *ReqResp) Reset()                    { *m = ReqResp{} }
func (m *ReqResp) String() string            { return proto.CompactTextString(m) }
func (*ReqResp) ProtoMessage()               {}
func (*ReqResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ReqResp) GetID() []byte {
	if m != nil {
		return m.ID
	}
	return nil
}

func (m *ReqResp) GetEntry() *Entry {
	if m != nil {
		return m.Entry
	}
	return nil
}

func (m *ReqResp) GetOptions() *RequestOptions {
	if m != nil {
		return m.Options
	}
	return nil
}

// Hexalog request options
type RequestOptions struct {
	// Index of the source in the PeerSet.  This is set internally by the log
	SourceIndex int32 `protobuf:"varint,1,opt,name=SourceIndex" json:"SourceIndex,omitempty"`
	// Set of peers for the request.
	PeerSet []*hexaring.Location `protobuf:"bytes,2,rep,name=PeerSet" json:"PeerSet,omitempty"`
	// Number of times to retry for a given request
	Retries int32 `protobuf:"varint,3,opt,name=Retries" json:"Retries,omitempty"`
	// Wait on ballot before returning
	WaitBallot bool `protobuf:"varint,4,opt,name=WaitBallot" json:"WaitBallot,omitempty"`
	// Wait for fsm to apply
	WaitApply bool `protobuf:"varint,5,opt,name=WaitApply" json:"WaitApply,omitempty"`
	// apply timeout in ms
	WaitApplyTimeout int32 `protobuf:"varint,6,opt,name=WaitApplyTimeout" json:"WaitApplyTimeout,omitempty"`
}

func (m *RequestOptions) Reset()                    { *m = RequestOptions{} }
func (m *RequestOptions) String() string            { return proto.CompactTextString(m) }
func (*RequestOptions) ProtoMessage()               {}
func (*RequestOptions) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *RequestOptions) GetSourceIndex() int32 {
	if m != nil {
		return m.SourceIndex
	}
	return 0
}

func (m *RequestOptions) GetPeerSet() []*hexaring.Location {
	if m != nil {
		return m.PeerSet
	}
	return nil
}

func (m *RequestOptions) GetRetries() int32 {
	if m != nil {
		return m.Retries
	}
	return 0
}

func (m *RequestOptions) GetWaitBallot() bool {
	if m != nil {
		return m.WaitBallot
	}
	return false
}

func (m *RequestOptions) GetWaitApply() bool {
	if m != nil {
		return m.WaitApply
	}
	return false
}

func (m *RequestOptions) GetWaitApplyTimeout() int32 {
	if m != nil {
		return m.WaitApplyTimeout
	}
	return 0
}

func init() {
	proto.RegisterType((*Entry)(nil), "hexatype.Entry")
	proto.RegisterType((*KeylogIndex)(nil), "hexatype.KeylogIndex")
	proto.RegisterType((*ReqResp)(nil), "hexatype.ReqResp")
	proto.RegisterType((*RequestOptions)(nil), "hexatype.RequestOptions")
}

func init() { proto.RegisterFile("types.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 395 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x52, 0x5d, 0x8b, 0xd4, 0x30,
	0x14, 0xa5, 0x1f, 0xd3, 0xd6, 0xdb, 0x71, 0x5d, 0xf2, 0xb0, 0x84, 0x45, 0xa4, 0x14, 0x84, 0xa2,
	0xd2, 0x85, 0xfa, 0x0b, 0x94, 0x11, 0x1c, 0x56, 0x71, 0xc9, 0x0a, 0x3e, 0x67, 0xea, 0xa5, 0x13,
	0xb6, 0xd3, 0x74, 0x93, 0x54, 0xb6, 0x4f, 0xfe, 0x59, 0x7f, 0x88, 0x24, 0xb6, 0xd3, 0x19, 0x7c,
	0xbb, 0xe7, 0xe4, 0xde, 0x7b, 0x7a, 0xee, 0x29, 0xa4, 0x66, 0xec, 0x51, 0x97, 0xbd, 0x92, 0x46,
	0x92, 0x64, 0x8f, 0x4f, 0xdc, 0x12, 0xd7, 0x6f, 0x1b, 0x61, 0xf6, 0xc3, 0xae, 0xac, 0xe5, 0xe1,
	0xc6, 0x92, 0xbb, 0x56, 0xd6, 0x0f, 0xae, 0x52, 0xa2, 0x6b, 0x6e, 0xb4, 0x51, 0x43, 0x6d, 0xa6,
	0xb1, 0xfc, 0x37, 0xac, 0x3e, 0x75, 0x46, 0x8d, 0xe4, 0x1a, 0x92, 0x3b, 0x85, 0xbf, 0x84, 0x1c,
	0x34, 0xf5, 0x32, 0xaf, 0x58, 0xb3, 0x23, 0x26, 0x2f, 0xe1, 0xd9, 0x77, 0x71, 0x40, 0x6d, 0xf8,
	0xa1, 0xa7, 0x7e, 0xe6, 0x15, 0x21, 0x5b, 0x08, 0x72, 0x05, 0xd1, 0x67, 0x14, 0xcd, 0xde, 0xd0,
	0x20, 0xf3, 0x8a, 0xe7, 0x6c, 0x42, 0xe4, 0x12, 0x82, 0x5b, 0x1c, 0x69, 0xe8, 0x96, 0xd9, 0x92,
	0x10, 0x08, 0x37, 0xdc, 0x70, 0xba, 0x72, 0x94, 0xab, 0x73, 0x01, 0xe9, 0x2d, 0x8e, 0xad, 0x6c,
	0xb6, 0xdd, 0x4f, 0x7c, 0x9a, 0x87, 0xbc, 0x65, 0x68, 0x59, 0xef, 0x9f, 0xad, 0xbf, 0x82, 0xe8,
	0x2b, 0x57, 0x0f, 0xa8, 0x9c, 0xec, 0x9a, 0x4d, 0x88, 0x50, 0x88, 0xad, 0x23, 0x81, 0x9a, 0x86,
	0x59, 0x50, 0xac, 0xd9, 0x0c, 0x73, 0x03, 0x31, 0xc3, 0x47, 0x86, 0xba, 0x27, 0x17, 0xe0, 0x6f,
	0x37, 0x93, 0x8a, 0xbf, 0xdd, 0x90, 0xd7, 0xd3, 0x19, 0x9c, 0x46, 0x5a, 0xbd, 0x28, 0xe7, 0x6b,
	0x96, 0x8e, 0x66, 0xd3, 0x91, 0x2a, 0x88, 0xbf, 0xf5, 0x46, 0xc8, 0x4e, 0x3b, 0xd1, 0xb4, 0xa2,
	0x4b, 0x23, 0xc3, 0xc7, 0x01, 0xb5, 0x99, 0xde, 0xd9, 0xdc, 0x98, 0xff, 0xf1, 0xe0, 0xe2, 0xfc,
	0x8d, 0x64, 0x90, 0xde, 0xcb, 0x41, 0xd5, 0xe8, 0x3c, 0xbb, 0xcf, 0x58, 0xb1, 0x53, 0x8a, 0xbc,
	0x83, 0xf8, 0x0e, 0x51, 0xdd, 0xa3, 0x75, 0x1d, 0x14, 0x69, 0x45, 0xca, 0x39, 0xc0, 0xf2, 0x8b,
	0xac, 0xb9, 0xdd, 0xc3, 0xe6, 0x16, 0x6b, 0x99, 0xe1, 0x3f, 0xcb, 0x81, 0xdb, 0x35, 0x43, 0xf2,
	0x0a, 0xe0, 0x07, 0x17, 0xe6, 0x23, 0x6f, 0x5b, 0x69, 0x5c, 0x14, 0x09, 0x3b, 0x61, 0x6c, 0xb2,
	0x16, 0x7d, 0xe8, 0xfb, 0x76, 0x74, 0xb1, 0x24, 0x6c, 0x21, 0xc8, 0x1b, 0xb8, 0x3c, 0x02, 0x9b,
	0xb7, 0x1c, 0x0c, 0x8d, 0x9c, 0xc0, 0x7f, 0xfc, 0x2e, 0x72, 0xff, 0xd3, 0xfb, 0xbf, 0x01, 0x00,
	0x00, 0xff, 0xff, 0xda, 0x0a, 0xdf, 0x64, 0x95, 0x02, 0x00, 0x00,
}
