// Code generated by protoc-gen-go.
// source: types.proto
// DO NOT EDIT!

/*
Package hexatype is a generated protocol buffer package.

It is generated from these files:
	types.proto

It has these top-level messages:
	Entry
	ReqResp
	RequestOptions
	KeyValuePair
*/
package hexatype

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import hexaring "github.com/hexablock/hexaring"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Hexalog entry
type Entry struct {
	Previous  []byte `protobuf:"bytes,1,opt,name=Previous,json=previous,proto3" json:"Previous,omitempty"`
	Timestamp uint64 `protobuf:"varint,2,opt,name=Timestamp,json=timestamp" json:"Timestamp,omitempty"`
	Height    uint32 `protobuf:"varint,3,opt,name=Height,json=height" json:"Height,omitempty"`
	Key       []byte `protobuf:"bytes,4,opt,name=Key,json=key,proto3" json:"Key,omitempty"`
	Data      []byte `protobuf:"bytes,5,opt,name=Data,json=data,proto3" json:"Data,omitempty"`
}

func (m *Entry) Reset()                    { *m = Entry{} }
func (m *Entry) String() string            { return proto.CompactTextString(m) }
func (*Entry) ProtoMessage()               {}
func (*Entry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Entry) GetPrevious() []byte {
	if m != nil {
		return m.Previous
	}
	return nil
}

func (m *Entry) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Entry) GetHeight() uint32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *Entry) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *Entry) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

// Request and response shared structure for hexalog
type ReqResp struct {
	ID      []byte          `protobuf:"bytes,1,opt,name=ID,json=iD,proto3" json:"ID,omitempty"`
	Entry   *Entry          `protobuf:"bytes,2,opt,name=Entry,json=entry" json:"Entry,omitempty"`
	Options *RequestOptions `protobuf:"bytes,3,opt,name=Options,json=options" json:"Options,omitempty"`
}

func (m *ReqResp) Reset()                    { *m = ReqResp{} }
func (m *ReqResp) String() string            { return proto.CompactTextString(m) }
func (*ReqResp) ProtoMessage()               {}
func (*ReqResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ReqResp) GetID() []byte {
	if m != nil {
		return m.ID
	}
	return nil
}

func (m *ReqResp) GetEntry() *Entry {
	if m != nil {
		return m.Entry
	}
	return nil
}

func (m *ReqResp) GetOptions() *RequestOptions {
	if m != nil {
		return m.Options
	}
	return nil
}

// Hexalog request options
type RequestOptions struct {
	// Index of the source in the PeerSet.  This is set internally by the log
	SourceIndex int32 `protobuf:"varint,1,opt,name=SourceIndex,json=sourceIndex" json:"SourceIndex,omitempty"`
	// Set of peers for the request.
	PeerSet []*hexaring.Location `protobuf:"bytes,2,rep,name=PeerSet,json=peerSet" json:"PeerSet,omitempty"`
}

func (m *RequestOptions) Reset()                    { *m = RequestOptions{} }
func (m *RequestOptions) String() string            { return proto.CompactTextString(m) }
func (*RequestOptions) ProtoMessage()               {}
func (*RequestOptions) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *RequestOptions) GetSourceIndex() int32 {
	if m != nil {
		return m.SourceIndex
	}
	return 0
}

func (m *RequestOptions) GetPeerSet() []*hexaring.Location {
	if m != nil {
		return m.PeerSet
	}
	return nil
}

type KeyValuePair struct {
	Key   []byte `protobuf:"bytes,1,opt,name=Key,json=key,proto3" json:"Key,omitempty"`
	Value []byte `protobuf:"bytes,2,opt,name=Value,json=value,proto3" json:"Value,omitempty"`
	Entry *Entry `protobuf:"bytes,3,opt,name=Entry,json=entry" json:"Entry,omitempty"`
}

func (m *KeyValuePair) Reset()                    { *m = KeyValuePair{} }
func (m *KeyValuePair) String() string            { return proto.CompactTextString(m) }
func (*KeyValuePair) ProtoMessage()               {}
func (*KeyValuePair) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *KeyValuePair) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *KeyValuePair) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *KeyValuePair) GetEntry() *Entry {
	if m != nil {
		return m.Entry
	}
	return nil
}

func init() {
	proto.RegisterType((*Entry)(nil), "hexatype.Entry")
	proto.RegisterType((*ReqResp)(nil), "hexatype.ReqResp")
	proto.RegisterType((*RequestOptions)(nil), "hexatype.RequestOptions")
	proto.RegisterType((*KeyValuePair)(nil), "hexatype.KeyValuePair")
}

func init() { proto.RegisterFile("types.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 344 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0xdf, 0x8b, 0xda, 0x40,
	0x10, 0xc7, 0xc9, 0x2f, 0xa3, 0x1b, 0x6b, 0xcb, 0x52, 0x4a, 0x90, 0x3e, 0x84, 0x40, 0x21, 0xd0,
	0x12, 0x21, 0xfd, 0x17, 0x2c, 0x54, 0x3c, 0x38, 0x59, 0x8f, 0x7b, 0x3b, 0xb8, 0x35, 0x0e, 0x66,
	0x51, 0xb3, 0x71, 0x77, 0x22, 0xe6, 0xe9, 0xfe, 0xf5, 0x23, 0x6b, 0x42, 0xb8, 0x97, 0x7b, 0x9b,
	0xf9, 0xcc, 0xec, 0xcc, 0xf7, 0x3b, 0x4b, 0x02, 0x6c, 0x2a, 0xd0, 0x69, 0xa5, 0x24, 0x4a, 0x3a,
	0x2e, 0xe0, 0xc6, 0x5b, 0x30, 0xff, 0x7d, 0x10, 0x58, 0xd4, 0xbb, 0x34, 0x97, 0xe7, 0x45, 0x0b,
	0x77, 0x27, 0x99, 0x1f, 0x4d, 0xa4, 0x44, 0x79, 0x58, 0x68, 0x54, 0x75, 0x8e, 0xdd, 0xb3, 0xf8,
	0x8d, 0x78, 0xff, 0x4a, 0x54, 0x0d, 0x9d, 0x93, 0xf1, 0x46, 0xc1, 0x55, 0xc8, 0x5a, 0x87, 0x56,
	0x64, 0x25, 0x53, 0x36, 0xae, 0xba, 0x9c, 0xfe, 0x24, 0x93, 0x27, 0x71, 0x06, 0x8d, 0xfc, 0x5c,
	0x85, 0x76, 0x64, 0x25, 0x2e, 0x9b, 0x60, 0x0f, 0xe8, 0x0f, 0x32, 0xfa, 0x0f, 0xe2, 0x50, 0x60,
	0xe8, 0x44, 0x56, 0xf2, 0x85, 0x8d, 0x0a, 0x93, 0xd1, 0x6f, 0xc4, 0x59, 0x43, 0x13, 0xba, 0x66,
	0x98, 0x73, 0x84, 0x86, 0x52, 0xe2, 0x2e, 0x39, 0xf2, 0xd0, 0x33, 0xc8, 0xdd, 0x73, 0xe4, 0x31,
	0x12, 0x9f, 0xc1, 0x85, 0x81, 0xae, 0xe8, 0x8c, 0xd8, 0xab, 0x65, 0xb7, 0xdc, 0x16, 0x4b, 0xfa,
	0xab, 0xd3, 0x66, 0x56, 0x06, 0xd9, 0xd7, 0xb4, 0xb7, 0x98, 0x1a, 0xcc, 0x3c, 0x30, 0xca, 0x33,
	0xe2, 0x3f, 0x56, 0x28, 0x64, 0xa9, 0x8d, 0x80, 0x20, 0x0b, 0x87, 0x46, 0x06, 0x97, 0x1a, 0x34,
	0x76, 0x75, 0xe6, 0xcb, 0x7b, 0x10, 0xbf, 0x92, 0xd9, 0xc7, 0x12, 0x8d, 0x48, 0xb0, 0x95, 0xb5,
	0xca, 0x61, 0x55, 0xee, 0xe1, 0x66, 0x54, 0x78, 0x2c, 0xd0, 0x03, 0xa2, 0x7f, 0x88, 0xbf, 0x01,
	0x50, 0x5b, 0xc0, 0xd0, 0x8e, 0x9c, 0x24, 0xc8, 0x68, 0xda, 0x1f, 0x35, 0x7d, 0x90, 0x39, 0x6f,
	0xe7, 0x30, 0xbf, 0xba, 0xb7, 0xc4, 0x2f, 0x64, 0xba, 0x86, 0xe6, 0x99, 0x9f, 0x6a, 0xd8, 0x70,
	0xa1, 0xfa, 0x6b, 0x58, 0xc3, 0x35, 0xbe, 0x13, 0xcf, 0x94, 0x8d, 0xbd, 0x29, 0xf3, 0xae, 0x6d,
	0x32, 0x98, 0x76, 0x3e, 0x33, 0xbd, 0x1b, 0x99, 0xef, 0xfb, 0xfb, 0x1e, 0x00, 0x00, 0xff, 0xff,
	0x2c, 0xf9, 0xd9, 0x81, 0x04, 0x02, 0x00, 0x00,
}
